import {
  defaultTiles,
  defaultPois,
  TILES,
  MAP_W,
  MAP_H,
} from './level1.js';

// ---------------------------------------------------------------------------
// mapStore — single source of truth for the LIVE map the game renders.
//
// Load priority:
//   1. an edited map saved in the browser (localStorage) from the in-game
//      editor, if it matches the current dimensions;
//   2. otherwise the default sketch layout generated by buildLevel().
//
// The editor writes here on every change (persists across reloads). "Export"
// serialises the same shape to a JSON file that can be committed as the
// canonical map later. Tiles are stored as one digit-string per row to stay
// compact in localStorage.
// ---------------------------------------------------------------------------

// Bump this when the committed map changes (dimensions or POIs) so stale
// browser saves from earlier iterations are discarded rather than loaded.
const KEY = 'drive.level1.map.v3';

export { TILES, MAP_W, MAP_H };

function clonePois(pois) {
  return pois.map((p) => ({ ...p }));
}

function defaultMap() {
  return { w: MAP_W, h: MAP_H, tiles: defaultTiles(), pois: defaultPois() };
}

function encodeRows(tiles) {
  return tiles.map((row) => row.join(''));
}

function decodeRows(rows) {
  return rows.map((s) => s.split('').map((c) => Number(c)));
}

function isValid(data) {
  return (
    data &&
    data.w === MAP_W &&
    data.h === MAP_H &&
    Array.isArray(data.tiles) &&
    data.tiles.length === MAP_H &&
    data.tiles.every((row) => typeof row === 'string' && row.length === MAP_W) &&
    Array.isArray(data.pois)
  );
}

// Guard against a corrupt/mismatched save stranding the car: the start must
// exist and sit on walkable ground.
function startIsOnGround(tiles, pois) {
  const start = pois.find((p) => p.type === 'start');
  if (!start) return false;
  const row = tiles[start.y];
  return !!row && row[start.x] === TILES.GROUND;
}

// Returns { w, h, tiles: number[][], pois: [{type,x,y,label}] }.
export function loadMap() {
  try {
    const raw = localStorage.getItem(KEY);
    if (raw) {
      const data = JSON.parse(raw);
      if (isValid(data)) {
        const tiles = decodeRows(data.tiles);
        const pois = clonePois(data.pois);
        if (startIsOnGround(tiles, pois)) {
          return { w: data.w, h: data.h, tiles, pois };
        }
      }
    }
  } catch (e) {
    // Corrupt/blocked storage — fall through to the default layout.
  }
  return defaultMap();
}

export function saveMap({ tiles, pois }) {
  try {
    const data = { w: MAP_W, h: MAP_H, tiles: encodeRows(tiles), pois };
    localStorage.setItem(KEY, JSON.stringify(data));
    return true;
  } catch (e) {
    return false;
  }
}

// Pretty JSON for download / committing as the canonical map.
export function exportJson({ tiles, pois }) {
  return JSON.stringify(
    { w: MAP_W, h: MAP_H, tiles: encodeRows(tiles), pois },
    null,
    2,
  );
}

export function clearSaved() {
  try {
    localStorage.removeItem(KEY);
  } catch (e) {
    // ignore
  }
}

export function hasSaved() {
  try {
    return !!localStorage.getItem(KEY);
  } catch (e) {
    return false;
  }
}
